ControleDeContatos/Models/ContatoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControleDeContatos.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
    }
}

ControleDeContatos/Models/ErrorViewModel.cs
using System;

namespace ControleDeContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControleDeContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;

        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();

            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            _contatoRepositorio.Adicionar(contato);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Editar(ContatoModel contato)
        {
            _contatoRepositorio.Editar(contato);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Apagar(int id)
        {
            bool apagou = _contatoRepositorio.Apagar(id);

            if (!apagou)
            {
                throw new Exception("Erro ao apagar contato");
            }

            return RedirectToAction("Index");
        }
    }
}

ControleDeContatos/Controllers/HomeController.cs
using ControleDeContatos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ControleDeContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ControleDeContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Apagar Contato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">
    <h1 class="display-4 text-center">Deseja realmente apagar o contato?</h1>

    <a class="pe-auto pl-5 ml-5" asp-controller="Contato" asp-action="Index"><i class="bi bi-arrow-left font-weight-bold" style="font-size:26px"></i></a>

    <div class="d-flex justify-content-center flex-column align-items-center pt-5">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <div class="d-flex justify-content-center flex-column align-items-center">
                    <div>
                        <p>Nome: <b>@Model.Nome</b></p>
                        <p>Email: <b>@Model.Email</b></p>
                        <p>Telefone: <b>@Model.Telefone</b></p>
                    </div>
                    <div class="d-flex w-50 justify-content-between align-items-center">
                        <a style="font-size: 36px" class="" asp-controller="Contato" asp-action="Index"><i class="bi text-danger bi-x-circle-fill"></i></a>
                        <a style="font-size: 36px" class="" asp-controller="Contato" asp-action="Apagar" asp-route-id="@Model.Id"><i class="bi text-primary bi-check-circle-fill"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ControleDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel

@{
    ViewData["Title"] = "Criar Contato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">
    <h1 class="display-4 text-center">Criar contato</h1>

    <a class="pe-auto pl-5 ml-5"  asp-controller="Contato" asp-action="Index"><i class="bi bi-arrow-left font-weight-bold" style="font-size:26px"></i></a>

    <div class="w-25 mx-auto">
        <form asp-controller="Contato" asp-action="Criar" method="post" class="mx-auto pt-5 text-start">
            <div class="mb-3">
                <label for="InputNome" class="form-label">Nome</label>
                <input type="text" asp-for="Nome" class="form-control" id="InputNome" placeholder="Eugênio Carvalho" />
            </div>
            <div class="mb-3">
                <label for="InputEmail" class="form-label">Email</label>
                <input type="email" asp-for="Email" class="form-control" id="InputEmail" placeholder="eugenio@email.com">
            </div>
            <div class="mb-3">
                <label for="InputTelefone" class="form-label">Telefone</label>
                <input type="tel" asp-for="Telefone" class="form-control" id="InputTelefone" placeholder="(11) 23456-7890">
            </div>
            <button type="submit" class="btn btn-primary d-inline-block w-100">Adicionar</button>
        </form>
    </div>
</div>

ControleDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar Contato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">
    <h1 class="display-4 text-center">Editar contato</h1>

    <a class="pe-auto pl-5 ml-5" asp-controller="Contato" asp-action="Index"><i class="bi bi-arrow-left font-weight-bold" style="font-size:26px"></i></a>

    <div class="w-25 mx-auto">
        <form asp-controller="Contato" asp-action="Editar" method="post" class="mx-auto pt-5 text-start">
            <div class="mb-3">
                <label for="InputNome" class="form-label">Nome</label>
                <input type="text" class="form-control" id="InputNome" asp-for="Nome"/>
            </div>
            <div class="mb-3">
                <label for="InputEmail" class="form-label">Email</label>
                <input type="email" class="form-control" id="InputEmail" asp-for="Email">
            </div>
            <div class="mb-3">
                <label for="InputTelefone" class="form-label">Telefone</label>
                <input type="tel" class="form-control" id="InputTelefone" asp-for="Telefone">
            </div>
            <button type="submit" class="btn btn-primary d-inline-block w-100">Editar</button>
        </form>
    </div>
</div>

ControleDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{

    ViewData["Title"] = "Listagem Contatos";
}

<div class="text-center">
    <div class="d-flex justify-content-end align-content-center">
        <a class="btn btn-outline-primary d-flex align-items-center" role="button" asp-controller="Contato" asp-action="Criar"><i class="bi bi-person-fill-add mr-2" style="font-size: 26px"></i> Adicionar contato</a>
    </div>

    <h1 class="display-4 pb-3">Listagem de contatos</h1>

    <table class="table table-striped progress-bar-striped table-bordered pt-2">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Telefone</th>
                <th scope="col" width="100">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ContatoModel contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Telefone</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Botões ações">
                                <a role="button" asp-route-id="@contato.Id" class="btn btn-primary" asp-controller="Contato" asp-action="Editar"><i class="bi bi-pencil-fill text-white"></i></a>
                                <a role="button" asp-route-id="@contato.Id" class="btn btn-danger" asp-controller="Contato" asp-action="ApagarConfirmacao"><i class="bi bi-trash3-fill text-white"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

ControleDeContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo</h1>
    <p>Sistema de controle de Contatos.</p>
</div>

ControleDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2023 - Controle de contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/js/mascara.js"></script>

    <script>
        aplicarMascaraTelefone();
    </script>
</body>
</html>